"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: unitree_go.msg.dds_
  IDL file: IMUState_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import unitree_go


@dataclass
@annotate.final
@annotate.autoid("sequential")
class IMUState_(idl.IdlStruct, typename="unitree_go.msg.dds_.IMUState_"):
    quaternion: types.array[types.float32, 4] # 四元数数据wxyz
    gyroscope: types.array[types.float32, 3] # 角速度信息（0-x, 1-y, 2-z）
    accelerometer: types.array[types.float32, 3] # 加速度信息（0-x, 1-y, 2-z）
    rpy: types.array[types.float32, 3] # 欧拉角信息：默认为弧度值（可按照实际情况改为角度值），可按照实际数值显示（弧度值范围：-7 - +7，显示3位小数）。（数组：0-roll（翻滚角），1-pitch（俯仰角），2-yaw（偏航角））
    temperature: types.uint8 # IMU 温度信息（摄氏度）


